### ISSUE TITLE
Project link is broken on PyPI

### ISSUE THREAD

**Issue by ForeverWintr** [Kemaweyan/singleton-decorator#1]
Hi, 

This isn't an issue with `singleton-decorator` per se, but the link from [PyPI](https://pypi.org/project/singleton-decorator/#description) to this repo is broken. 

It should be
`https://github.com/Kemaweyan/singleton-decorator`, not
`https://github.com/Kemaweyan/singleton_decorator`

Cool project!

**Comment by Kemaweyan** [comment]
Thanks for feedback. I changed the name on GitHub to make the link valid.

**Comment by ForeverWintr** [comment]
Great, thanks!
